# DB接続情報（環境変数から読み込む。未設定の場合はローカルに接続）
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workout_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:isayamayuto}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_password}

# Hibernateの設定
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}